---
title: "SCDH Schedule"
author: "Ben Matthews"
date: "2023-07-17"
output: github_document
---


# Day One: Getting Started

LLTC_2.14 - Teaching Studio, [Lister Learning and Teaching Centre](https://www.ed.ac.uk/files/atoms/files/lister_learning_teaching_centre.pdf) | online

- 09:30 – Welcome and registration
- 10:00 – Icebreaker and Hackathon introduction
- 10:30 – Presentations: The how and why of the SCJS
  - Scottish Government Justice Analytical Services (JAS): The why of the SCJS
  - Ipsos/JAS: The how of the SCJS
  - JAS: The analysis datasets
- 11:15 – Break
- 11:30 – Presentations: Justice stakeholders and the SCJS
  - Scottish Police Authority
  - Community Justice Scotland
  - Scottish Government - Violence Against Women and Girls
- 12:15 – Team discussion – initial project thoughts
- 13:00 - Lunch
- 13:45 – ‘Reset’ (unstructured time: return to work on Hackathon project, or free time to stretch the legs etc.)
- 14:30 – 3 min presentation of initial ideas to whole group
- 14:45 – Project development
- 15:45 – Projects agreed
- 16:00 – Depart

## Participant dinner
- 18:00 - Dinner at [David Bann](https://www.davidbann.co.uk/)
 

# Day Two: Data Day

LLTC_2.14 - Teaching Studio, [Lister Learning and Teaching Centre](https://www.ed.ac.uk/files/atoms/files/lister_learning_teaching_centre.pdf) | online

- 09:30 – Review and plan
- 10:00 – Analysis
- 11:15 – Break
- 11:30 – Analysis
- 13:00 - Lunch
- 13:45 – ‘Reset’
- 14:30 – Whole group check-in
- 14:45 – Analysis
- 16:00 – Depart 


# Day Three: Writing Day
University of Stirling, Campus Central (CC.04) | online

- 09:30 – Writing retreat activities
- 10:00 – Writing
- 11:15 – Break
- 11:30 – Writing
- 13:00 - Lunch
- 13:45 – ‘Reset’
- 14:30 – Final writing sprint
- 15:00 – Reading and feedback session with stakeholders
- 16:00 – Depart
